import { serve } from "https://deno.land/std@0.177.0/http/server.ts"
import { Resend } from "npm:resend@2.0.0"

const resend = new Resend(Deno.env.get('RESEND_API_KEY') as string);

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { email, country, updateTitle, updateDate } = await req.json();

    const data = await resend.emails.send({
      from: 'Immigration Radar <alerts@resend.dev>',
      to: email, // If using Resend free tier, this MUST be the verified sender email.
      subject: `Urgent Immigration Intelligence: ${country}`,
      html: `
        <div style="font-family: 'Inter', sans-serif; max-width: 600px; margin: 0 auto; color: #1f2937; line-height: 1.6;">
          <h2 style="color: #2DA099; border-bottom: 2px solid #e5e7eb; padding-bottom: 12px;">Watchlist Trigger: ${country}</h2>
          <p>A new critical immigration rule change has been detected on your strategic watchlist.</p>
          <div style="background-color: #f9fafb; border: 1px solid #e5e7eb; padding: 24px; border-radius: 8px; margin: 24px 0;">
             <p style="margin-top:0;"><strong>Classification:</strong> ${updateTitle}</p>
             <p style="margin-bottom:0;"><strong>Effective Date:</strong> ${updateDate}</p>
          </div>
          <p style="color: #4b5563; font-size: 14px;">This framework shift may impact your current planning timelines or financial strategy. Please refer to your central command hub to initiate re-calculation of the pathway.</p>
          <br/>
          <a href="https://global-watcher.vercel.app/watchlist" style="background-color: #2DA099; color: white; padding: 14px 28px; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block;">View Command Dashboard</a>
          
          <div style="margin-top: 48px; font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 16px;">
            Confidential intelligence report generated by Immigration Radar Engine.<br>
            You are receiving this because this jurisdiction is active on your Watchlist.
          </div>
        </div>
      `
    });

    return new Response(JSON.stringify(data), {
      status: 200,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (error: any) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
})
