/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as VisaCategoriesRouteImport } from './routes/visa-categories'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as CountriesIndexRouteImport } from './routes/countries.index'
import { Route as CountriesCodeRouteImport } from './routes/countries.$code'
import { Route as UpdatesIndexRouteImport } from './routes/updates.index'
import { Route as UpdatesIdRouteImport } from './routes/updates.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaCategoriesRoute = VisaCategoriesRouteImport.update({
  id: '/visa-categories',
  path: '/visa-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesCodeRoute = CountriesCodeRouteImport.update({
  id: '/countries/$code',
  path: '/countries/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesIndexRoute = UpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesIdRoute = UpdatesIdRouteImport.update({
  id: '/updates/$id',
  path: '/updates/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/eligibility': typeof EligibilityRoute
  '/reset-password': typeof ResetPasswordRoute
  '/timeline': typeof TimelineRoute
  '/update-password': typeof UpdatePasswordRoute
  '/visa-categories': typeof VisaCategoriesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/users': typeof AdminUsersRoute
  '/countries/$code': typeof CountriesCodeRoute
  '/updates/$id': typeof UpdatesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/countries/': typeof CountriesIndexRoute
  '/updates/': typeof UpdatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/eligibility': typeof EligibilityRoute
  '/reset-password': typeof ResetPasswordRoute
  '/timeline': typeof TimelineRoute
  '/update-password': typeof UpdatePasswordRoute
  '/visa-categories': typeof VisaCategoriesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/users': typeof AdminUsersRoute
  '/countries/$code': typeof CountriesCodeRoute
  '/updates/$id': typeof UpdatesIdRoute
  '/admin': typeof AdminIndexRoute
  '/countries': typeof CountriesIndexRoute
  '/updates': typeof UpdatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/eligibility': typeof EligibilityRoute
  '/reset-password': typeof ResetPasswordRoute
  '/timeline': typeof TimelineRoute
  '/update-password': typeof UpdatePasswordRoute
  '/visa-categories': typeof VisaCategoriesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/users': typeof AdminUsersRoute
  '/countries/$code': typeof CountriesCodeRoute
  '/updates/$id': typeof UpdatesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/countries/': typeof CountriesIndexRoute
  '/updates/': typeof UpdatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/calculator'
    | '/compare'
    | '/eligibility'
    | '/reset-password'
    | '/timeline'
    | '/update-password'
    | '/visa-categories'
    | '/profile'
    | '/watchlist'
    | '/admin/content'
    | '/admin/users'
    | '/countries/$code'
    | '/updates/$id'
    | '/admin/'
    | '/countries/'
    | '/updates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calculator'
    | '/compare'
    | '/eligibility'
    | '/reset-password'
    | '/timeline'
    | '/update-password'
    | '/visa-categories'
    | '/profile'
    | '/watchlist'
    | '/admin/content'
    | '/admin/users'
    | '/countries/$code'
    | '/updates/$id'
    | '/admin'
    | '/countries'
    | '/updates'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/calculator'
    | '/compare'
    | '/eligibility'
    | '/reset-password'
    | '/timeline'
    | '/update-password'
    | '/visa-categories'
    | '/_authenticated/profile'
    | '/_authenticated/watchlist'
    | '/admin/content'
    | '/admin/users'
    | '/countries/$code'
    | '/updates/$id'
    | '/admin/'
    | '/countries/'
    | '/updates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalculatorRoute: typeof CalculatorRoute
  CompareRoute: typeof CompareRoute
  EligibilityRoute: typeof EligibilityRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TimelineRoute: typeof TimelineRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  VisaCategoriesRoute: typeof VisaCategoriesRoute
  CountriesCodeRoute: typeof CountriesCodeRoute
  UpdatesIdRoute: typeof UpdatesIdRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  UpdatesIndexRoute: typeof UpdatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visa-categories': {
      id: '/visa-categories'
      path: '/visa-categories'
      fullPath: '/visa-categories'
      preLoaderRoute: typeof VisaCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$code': {
      id: '/countries/$code'
      path: '/countries/$code'
      fullPath: '/countries/$code'
      preLoaderRoute: typeof CountriesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/': {
      id: '/updates/'
      path: '/updates'
      fullPath: '/updates/'
      preLoaderRoute: typeof UpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/$id': {
      id: '/updates/$id'
      path: '/updates/$id'
      fullPath: '/updates/$id'
      preLoaderRoute: typeof UpdatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CalculatorRoute: CalculatorRoute,
  CompareRoute: CompareRoute,
  EligibilityRoute: EligibilityRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TimelineRoute: TimelineRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  VisaCategoriesRoute: VisaCategoriesRoute,
  CountriesCodeRoute: CountriesCodeRoute,
  UpdatesIdRoute: UpdatesIdRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  UpdatesIndexRoute: UpdatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
